### PR TITLE
Add GigIndia to repo

### PR DESCRIPTION
**Pull request by akash-joshi**

### CODE REVIEW

**Comment by kamleshchandnani** [comment]
Hey @akash-joshi,
Thank you so much for your contribution 🎉 

I urge you to elaborate more on the rounds and it's details. Imagine you're a person who's unwaware about GigIndia and would like to get more and more in depth detail of the interview process what are the basic things you would look for and put those details 🙂

**Comment by kamleshchandnani** [comment]
In addition to the info above can you add some more info in the comments here? I'll be updating the format to include information of the reviewer.
Information needed:
1. Name
2. Twitter Handle
3. Role/Level (description of what role you had applied/adding reviews for)

**Comment by kamleshchandnani** [comment]
Hi @akash-joshi,
Are you considering this and taking it up?

**Comment by kamleshchandnani** [comment]
You can refer to the format for reviewer info [here](https://github.com/kamleshchandnani/awesome-interview-process/blob/master/content/companies/02-gatsby.md#reviewer-info)

**Comment by akash-joshi** [comment]
Hey @kamleshchandnani , closing this for now as I work here rn. I'll probably complete when I'm done 😝

**Pull request closed without merging**
